- name : settingup cart 
  hosts : cart
  become : yes
  tasks :
    - name : disabling nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    - name : enabling nodejs:20
      ansible.builtin.command : dnf module enable nodejs:20 -y
    - name : installing nodejs
      ansible.builtin.package:
        name : nodejs 
        state : present
    - name: creating roboshop user
      ansible.builtin.user:
        name: roboshop
        comment : Roboshop system user
        system: true
        shell: /sbin/nologin
        home: /app 
    
    - name : removing app 
      ansible.builtin.file:
        path : /app
        state : absent 
    
    - name : creating app
      ansible.builtin.file:
        path : /app
        state : directory

    - name: Delete cart file
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent

    - name : downloading the application
      ansible.builtin.get_url:
        url : https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
        dest : /tmp/cart.zip
    
    - name : unzipping the application
      ansible.builtin.unarchive:
        src : /tmp/cart.zip
        dest : /app
        remote_src : yes

    - name: install dependencies
      community.general.npm:
        path: /app
      
    - name : copying cart services
      ansible.builtin.copy:
        src : cart.service
        dest : /etc/systemd/system/cart.service

    - name : reloading cart
      ansible.builtin.systemd_service:
        name : cart 
        enabled : yes
        state : started
        daemon_reload : true
    
