- name : nodejs setup
  ansible.builtin.import_role:  
    name : common
    tasks_from : nodejs
    
- name: install dependencies
  community.general.npm:
    path: /app
  
- name : copying cart services
  ansible.builtin.copy:
    src : cart.service
    dest : /etc/systemd/system/cart.service

- name : reloading cart
  ansible.builtin.systemd_service:
    name : cart 
    enabled : yes
    state : started
    daemon_reload : true
    
